# This YAML configuration file is used to set up and configure the Slides Search RAG template.
# It defines various components such as data sources, language models, embedders, indices, and data schema.
# Each section is configured to specify how the template should process and handle data for generating responses.
# You can learn more about the YAML syntax here: https://pathway.com/developers/templates/configure-yaml



# $sources defines the data sources used to read the data which will be indexed in the RAG.
# You can learn more how to configure data sources here:
# https://pathway.com/developers/templates/yaml-examples/data-sources-examples

sources:
  # File System connector, reading data locally.
  - !pw.io.fs.read
    path: data
    format: binary
    with_metadata: true

  # Uncomment to use the SharePoint connector
  # - !pw.xpacks.connectors.sharepoint.read 
  #   url: $SHAREPOINT_URL
  #   tenant: $SHAREPOINT_TENANT
  #   client_id: $SHAREPOINT_CLIENT_ID
  #   cert_path: sharepointcert.pem
  #   thumbprint: $SHAREPOINT_THUMBPRINT
  #   root_path: $SHAREPOINT_ROOT
  #   with_metadata: true
  #   refresh_interval: 30

  # Uncomment to use the Google Drive connector
  # - !pw.io.gdrive.read
  #   object_id: $DRIVE_ID
  #   service_user_credentials_file: gdrive_indexer.json
  #   file_name_pattern:
  #     - "*.pdf"
  #     - "*.pptx"
  #   object_size_limit: null
  #   with_metadata: true
  #   refresh_interval: 30

# Configures the LLM model settings for generating responses.
# The list of available Pathway LLM wrappers is available here:
# https://pathway.com/developers/api-docs/pathway-xpacks-llm/llms
# You can learn more about those in our documentation:
# https://pathway.com/developers/templates/rag-customization/llm-chats

llm: !pw.xpacks.llm.llms.OpenAIChat
  model: "gpt-4o"
  retry_strategy: !pw.udfs.ExponentialBackoffRetryStrategy
    max_retries: 6
    initial_delay: 2500
    backoff_factor: 2.5
  cache_strategy: !pw.udfs.DefaultCache {}
  temperature: 0.0
  capacity: 8 # reduce this in case you are hitting API throttle limits
  async_mode: "fully_async"

# Specifies the embedder model for converting text into embeddings.
$embedder: !pw.xpacks.llm.embedders.OpenAIEmbedder
  cache_strategy: !pw.udfs.DefaultCache {}
  retry_strategy: !pw.udfs.ExponentialBackoffRetryStrategy {}
  model: "text-embedding-3-small"

# Sets up the retriever factory for indexing and retrieving documents.
retriever_factory: !pw.indexing.UsearchKnnFactory
  reserved_space: 1000
  embedder: $embedder
  metric: !pw.indexing.USearchMetricKind.COS

# Defines the schema used for the data extraction of each slide.
details_schema:
  category:
    type: option
    values:
      - "Problem Statement"
      - "Solution Overview"
      - "Product/Service Demo"
      - "Benefits and Value Proposition"
      - "Competitive Landscape"
      - "Case Studies and Testimonials"
      - "Features and Specifications"
      - "How it Works"
      - "Return on Investment (ROI) and Cost Savings"
      - "Call to Action (CTA) and Next Steps"
      - "Company Overview and Credentials"
      - "Market Opportunity and Trends"
      - "Customer Success Stories and Use Cases"
      - "Pricing and Packaging"
      - "Implementation and Support"
  tags:
    type: list[str]
    description: "Tags associated with the slide. For example ['price', 'shopping', 'consumer'] or ['beverage', 'cola', 'manufacturing']"
  title:
    type: str
    description: "Title of the slide"
  main_color:
    type: str
    description: "Most common color. For example 'black', 'blue', 'yellow'"
  language:
    type: str
    description: "Language of the slide. For example 'fr', 'en'"
  has_images:
    type: bool
    description: "Whether the slide contains photographs"

# Change host and port of the webserver by uncommenting these lines
# host: "0.0.0.0"
# port: $PATHWAY_PORT

# By default, caching is enabled for UDFs with cache_strategy set.
# You can disable it by uncommenting the following line.
# persistence_mode: null
# You can also set persistence_mode to !pw.PersistenceMode.PERSISTING to enable persistence
# across restarts.
# By default, when enabled, Cache is stored in .Cache directory.
# You can customize the location by uncommenting and modifying the following lines:
# persistence_backend: !pw.persistence.Backend.filesystem
#   path: ".Cache"

# If `terminate_on_error` is true then the program will terminate whenever any error is encountered.
# Defaults to false, uncomment the following line if you want to set it to true
# terminate_on_error: true
