FROM pathwaycom/pathway:0.13.2

ENV PYTHONUNBUFFERED=1

WORKDIR /ui

COPY ui/requirements-ui.txt requirements-ui.txt

RUN pip install -U --no-cache-dir -r requirements-ui.txt

COPY ui/ .

EXPOSE 8501

CMD [ "streamlit", "run", "ui.py" ]
